#below addtions are for hos
- type: loadout
  id: UniformHeadSecurityThong
  equipment:
    jumpsuit: ClothingUniformHeadSecurityThong

- type: loadout
  id: HandsHeadSecurityWarmers
  equipment:
    gloves: ClothingHandsHeadSecurityWarmers

- type: loadout
  id: UnderSocksHeadSecurity
  equipment:
    shoes: ClothingUnderSocksHeadSecurity
